#░  ░░░░  ░░        ░░░      ░░░       ░░░░      ░░░░      ░░░  ░░░░  ░░░      ░░░        ░
#▒  ▒▒▒▒  ▒▒  ▒▒▒▒▒▒▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒▒▒▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒▒▒▒  ▒▒▒▒
#▓        ▓▓      ▓▓▓▓  ▓▓▓▓  ▓▓  ▓▓▓▓  ▓▓▓      ▓▓▓  ▓▓▓▓▓▓▓▓        ▓▓  ▓▓▓▓  ▓▓▓▓▓  ▓▓▓▓
#█  ████  ██  ████████        ██  ████  ████████  ██  ████  ██  ████  ██        █████  ████
#█  ████  ██        ██  ████  ██       ████      ████      ███  ████  ██  ████  █████  ████

# This is the main configuration file for the plugin.
# You can customize the join, leave, and chat messages here.

# Change formating of messages here.
# You can use the following placeholders (placeholders from PlaceholderAPI are also supported):
# {head} - The player's head (if available)
# {player} - The player's name
# {message} - The chat message (only for chat format)
# Color codes are supported using the § symbol followed by a color code (e.g., §a for green).

chat:
  enabled: true
  logging: true
  format: "<white>{head} {player}: <gray>{message}"

join:
  enabled: true
  format: "<yellow>{head} {player} joined the server"

leave:
  enabled: true
  format: "<yellow>{head} {player} has left the server"

# Changing this little guy will break everything. Do not change it. Promise?
config-version: 2