#░  ░░░░  ░░        ░░░      ░░░       ░░░░      ░░░░      ░░░  ░░░░  ░░░      ░░░        ░
#▒  ▒▒▒▒  ▒▒  ▒▒▒▒▒▒▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒▒▒▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒  ▒▒▒▒  ▒▒▒▒▒  ▒▒▒▒
#▓        ▓▓      ▓▓▓▓  ▓▓▓▓  ▓▓  ▓▓▓▓  ▓▓▓      ▓▓▓  ▓▓▓▓▓▓▓▓        ▓▓  ▓▓▓▓  ▓▓▓▓▓  ▓▓▓▓
#█  ████  ██  ████████        ██  ████  ████████  ██  ████  ██  ████  ██        █████  ████
#█  ████  ██        ██  ████  ██       ████      ████      ███  ████  ██  ████  █████  ████

# This is the main configuration file for the plugin.
# You can customize the join, leave, and chat messages here.

# SUPPORT SERVER:
# https://dsc.gg/drmcld

# Change formating of messages here.
# You can use the following placeholders (placeholders from PlaceholderAPI are also supported):
# {head} - The player's head (if available)
# {player} - The player's name
# {message} - The chat message (only for chat format)
# Color codes are supported using the § symbol followed by a color code (e.g., §a for green).

# Changing this little guy will break everything. Do not change it. Promise?
config-version: 3

chat:
  enabled: true
  logging: true
  format: "<white>{head} {player}: <gray>{message}"
  cooldown: 0
  cooldown-message: "<red>You are sending messages too quickly! Please wait {time} seconds."
  cooldown-bypass-permission: "headschat.bypass.cooldown"

name-format:
  enabled: true
  dialog:
    name: "Change your Display Name"
    confirm: "<green>Confirm"
    confirm-tooltip: "Click to confirm your new display name"
    cancel: "<red>Cancel"
    cancel-tooltip: "Click to cancel changing your display name"
    prompt: "Please enter your new display name:"

dm:
  enabled: true
  format: "[<white>{head} {player} -> {target_head} {target}]: <gray>{message}"

join:
  enabled: true
  format: "<yellow>{head} {player} joined the server"

leave:
  enabled: true
  format: "<yellow>{head} {player} has left the server"