name: HeadsChat
version: '1.1.1'
main: dev.funa.headsChat.HeadsChat
api-version: '1.21'
softdepend: ["PlaceholderAPI"]

commands:
  headschat:
    description: Reload the HeadsChat plugin configuration.
    usage: /headschatreload <subcommand>
    permission: headschat.command
    permission-message: You don't have permission to use this command!