name: HeadsChat
version: '1.2.1'
main: dev.funa.headsChat.HeadsChat
api-version: '1.21'
folia-supported: true
softdepend: ["PlaceholderAPI"]

commands:
  headschat:
    description: Reload the HeadsChat plugin configuration.
    usage: /headschatreload <subcommand>
    permission: headschat.command
    permission-message: You don't have permission to use this command!
  msg:
    description: Send a private message to another player.
    usage: /<command> [player] <message>
    aliases: [dm, tell, whisper]
    permission: headschat.msg
    permission-message: You don't have permission to use this command!
